export const decisionCopy = {
  fr: {
    notEvaluated: "Non évalué", measured: "Note mesurée", provisional: "Note provisoire",
    verdict: { critical: "Des constats critiques restent à traiter", important: "Des points importants sont à examiner", opportunity: "Des pistes d’amélioration sont disponibles", empty: "Aucun constat remonté parmi les contrôles mesurés", unavailable: "Le diagnostic ne permet pas de conclure sur une note globale" },
    favourable: "La moyenne est favorable ; elle ne supprime pas les constats critiques.",
    empty: "L’absence de constat ne prouve pas la conformité ni l’absence de défaut.",
    scope: "Page analysée", siteTitle: "Titre HTML", dateUnknown: "Date non renseignée", scopeUnknown: "Périmètre non renseigné",
    privacy: "Rapport accessible à toute personne disposant du lien. Il n’est pas indexé par les moteurs de recherche.",
    privateLabel: "Accès par lien", actions: "Consulter le plan d’action", method: "Méthode et limites", methodLink: "Comprendre la mesure",
    antiBot: "Une protection anti-bot limite le périmètre mesuré. Les contrôles bloqués ne prouvent pas un défaut du site.",
    coverageUnknown: "Couverture détaillée non disponible dans ce rapport.",
    insufficient: "Couverture limitée", coverageUnavailable: "Aucun poids mesuré", coverageExplain: "Part du poids des contrôles mesurés dans le barème attendu, hors contrôles non applicables.",
    completenessExplain: "La complétude indique la part des modules évalués ; elle ne mesure pas la couverture pondérée du barème.",
    confidenceExplain: "La confiance qualifie chaque constat ; elle ne se déduit ni de la note ni de la couverture.",
    automaticLimit: "L’accessibilité automatique ne certifie pas la conformité RGAA ou WCAG. Des vérifications humaines restent nécessaires.",
    lighthouse: "Les notes Lighthouse sont des scores d’outil, distincts des notes de domaine Argos.",
    source: "Sources présentes dans le rapport", sourcesUnknown: "Sources non renseignées", versions: "Versions disponibles", versionsUnknown: "Version du barème non renseignée",
    scoring: "Barème Argos", coverageVersion: "Couverture", editorial: "Catalogue éditorial affiché", evidence: "Preuves d’accessibilité", mapping: "Correspondances d’accessibilité", compliance: "Qualification d’accessibilité",
    missingModules: "Modules avec contrôles non mesurés", checks: "État des contrôles", generalMethod: "Lire la méthode de scoring Argos",
    unknownFindings: "Constats sans domaine renseigné", domainCoverage: "Couverture pondérée", domainScore: "Note Argos",
    domainDescriptions: {
      performance: "Chargement et interactions dans les conditions de la mesure.",
      security: "En-têtes HTTP, connexion chiffrée et signaux de sécurité observés.",
      seo: "Structure de page, métadonnées et signaux d’indexabilité observés.",
      a11y: "Contrôles automatiques des contenus et interactions accessibles.",
    },
    ranking: "Classement des priorités", fingerprint: "Empreinte du barème",
  },
  en: {
    notEvaluated: "Not evaluated", measured: "Measured score", provisional: "Provisional score",
    verdict: { critical: "Critical findings still need attention", important: "Important findings need review", opportunity: "Improvement opportunities are available", empty: "No findings reported among measured checks", unavailable: "The diagnosis does not support a global score" },
    favourable: "The average is favourable; critical findings still require attention.",
    empty: "No findings does not prove compliance or the absence of defects.",
    scope: "Analysed page", siteTitle: "HTML title", dateUnknown: "Date not provided", scopeUnknown: "Scope not provided",
    privacy: "Anyone with the link can access this report. Search engines do not index it.",
    privateLabel: "Access by link", actions: "Open the action plan", method: "Method and limitations", methodLink: "Understand the measurement",
    antiBot: "An anti-bot protection limits the measured scope. Blocked checks do not prove a site defect.",
    coverageUnknown: "Detailed coverage is not available in this report.",
    insufficient: "Limited coverage", coverageUnavailable: "No measured weight", coverageExplain: "Share of measured check weights in the expected scoring policy, excluding checks that do not apply.",
    completenessExplain: "Completeness indicates the share of evaluated modules; it does not measure weighted scoring coverage.",
    confidenceExplain: "Confidence qualifies each finding; it cannot be inferred from the score or coverage.",
    automaticLimit: "Automated accessibility does not certify RGAA or WCAG compliance. Human checks are still necessary.",
    lighthouse: "Lighthouse scores are tool scores, separate from Argos domain scores.",
    source: "Sources present in the report", sourcesUnknown: "Sources not provided", versions: "Available versions", versionsUnknown: "Scoring policy version not provided",
    scoring: "Argos scoring policy", coverageVersion: "Coverage", editorial: "Displayed editorial catalogue", evidence: "Accessibility evidence", mapping: "Accessibility mapping", compliance: "Accessibility qualification",
    missingModules: "Modules with unmeasured checks", checks: "Check states", generalMethod: "Read the Argos scoring method",
    unknownFindings: "Findings with no domain provided", domainCoverage: "Weighted coverage", domainScore: "Argos score",
    domainDescriptions: {
      performance: "Loading and interactions under the measurement conditions.",
      security: "Observed HTTP headers, encrypted connection and security signals.",
      seo: "Observed page structure, metadata and indexing signals.",
      a11y: "Automated checks of accessible content and interactions.",
    },
    ranking: "Priority ranking", fingerprint: "Scoring policy fingerprint",
  },
} as const;
