export const reportReadingCopy = {
  fr: {
    navigation: "Lecture du rapport", overview: "Vue d’ensemble", actions: "Plan d’action", technical: "Constats techniques",
    domain: "Domaine", allDomains: "Tous les domaines", missing: "Ce constat est absent de ce rapport. Vous pouvez consulter les constats disponibles.",
    observation: "Ce qui a été observé", impact: "Pourquoi s’en occuper", recommendation: "Action recommandée", verification: "Comment vérifier",
    technicalTitle: "Titre technique original", technicalId: "Identifiant technique", evidence: "Preuve technique", missingMeasure: "Mesure détaillée non disponible dans ce rapport.",
    originalObservation: "Observation technique originale", catalogueVersion: "Version du contenu", favourableCritical: "La note globale reste une moyenne : des constats critiques sont présents.",
    unknownConfidence: "Confiance non renseignée", source: "Source", summary: "Synthèse des constats", summaryFacts: "{total} constats uniques : {critical} critiques, {important} importants, {opportunity} opportunités.",
    next: "Confirmer les signaux prioritaires, estimer les corrections puis re-mesurer dans des conditions comparables.",
    limits: "Les résultats décrivent uniquement le périmètre mesuré ; ils ne garantissent ni conformité ni résultat commercial.",
    partial: "Analyse partielle : les constats disponibles ne couvrent pas tous les contrôles.", historicalCoverage: "Couverture détaillée non disponible dans ce rapport.",
    moduleCompleteness: "Complétude opérationnelle des modules", coverage: "Couverture pondérée du barème", score: "Score Argos", clear: "Afficher tous les constats", estimated: "Transfert estimé",
    lighthouseRatio: "Score Lighthouse normalisé (ratio)",
    units: { ms: "ms", bytes: "octets", count: "éléments", days: "jours", "score/100": "/100", ratio: "ratio sans unité", unitless: "sans unité" },
  },
  en: {
    navigation: "Report reading", overview: "Overview", actions: "Action plan", technical: "Technical findings",
    domain: "Domain", allDomains: "All domains", missing: "This finding is absent from this report. You can browse the available findings.",
    observation: "What was observed", impact: "Why it matters", recommendation: "Recommended action", verification: "How to verify",
    technicalTitle: "Original technical title", technicalId: "Technical identifier", evidence: "Technical evidence", missingMeasure: "Detailed measurement is not available in this report.",
    originalObservation: "Original technical observation", catalogueVersion: "Content version", favourableCritical: "The global score remains an average: critical findings are present.",
    unknownConfidence: "Confidence not provided", source: "Source", summary: "Findings summary", summaryFacts: "{total} unique findings: {critical} critical, {important} important, {opportunity} opportunities.",
    next: "Confirm priority signals, estimate corrections, then re-measure under comparable conditions.",
    limits: "Results describe only the measured scope; they guarantee neither compliance nor business outcomes.",
    partial: "Partial analysis: available findings do not cover every check.", historicalCoverage: "Detailed coverage is not available in this report.",
    moduleCompleteness: "Operational module completeness", coverage: "Weighted scoring coverage", score: "Argos score", clear: "Show all findings", estimated: "Estimated transfer",
    lighthouseRatio: "Normalised Lighthouse score (ratio)",
    units: { ms: "ms", bytes: "bytes", count: "items", days: "days", "score/100": "/100", ratio: "unitless ratio", unitless: "unitless" },
  },
} as const;
